### ISSUE TITLE
Rolling restart/update at every sync cycle since v1.6.1

### ISSUE THREAD

**Issue by mboutet** [zalando/postgres-operator#1377]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**  AKS 1.19.7
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

Ever since version 1.6.1, the postgres cluster goes through a rolling restart/update at every sync cycle.

Gist containing the `OperatorConfiguration`, `postgresql` and operator logs for 1.6.0 and 1.6.1:

https://gist.github.com/mboutet/9e1a3d6b6164908fd21caa406b1e8921

`OperatorConfiguration` and `postgresql` are the same and the only variable is the operator's version.

**Comment by FxKu** [comment]
@mboutet can you add an additional pod capability (e.g. SYS_NICE if your K8s allows it)? This is a new config option. I think it might cause the diff during SYNC.

**Comment by machine424** [comment]
@FxKu, I think this is it, `generateCapabilities` in [here](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/k8sres.go#L323) returns a `v1.Capabilities{Add:[]v1.Capability{} ...` if no `capabilities` is provided (because of the `make`), the empty slice `Add` is then omitted by the Kube API (see [here](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2163)), so the operator retrieves `v1.Capabilities{Add:[]v1.Capability(nil) ...` ...

**Comment by FxKu** [comment]
Yes, probably `capabilities: {}` in the actual Spec vs. `capabilities: add: nil` from generated StatefulSet. Will fix this next week.

**Comment by mboutet** [comment]
@FxKu, the workaround of adding a pod capability (`SYS_NICE` as suggested) works. Thank you!

**Comment by yfoelling** [comment]
@FxKu can we have another Release containing that fix?

**Comment by harlanbarnes** [comment]
FWIW, if you are using the helm chart (and your system supports `SYS_NICE`), adding this `--set` will perform the workaround described above:

```
--set configKubernetes.additional_pod_capabilities=SYS_NICE
```

**Comment by ben-pr-p** [comment]
> @FxKu, the workaround of adding a pod capability (`SYS_NICE` as suggested) works. Thank you!

Do you have an example of how to do this if you're deploying without helm?

**Comment by GMartinez-Sisti** [comment]
@ben-pr-p you can run the steps from [here](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#helm-chart), and instead of `helm install postgres-operator ./charts/postgres-operator` run `helm template ./charts/postgres-operator --set configKubernetes.additional_pod_capabilities=SYS_NICE` and it will export the yaml result.

**Comment by egov-moldova** [comment]
Still, this prevents instantiating clusters in restricted environments, such as OpenShift of namespaces with a restricted PSP.
Would you please release a new version?
