### ISSUE TITLE
consider switching from glide to dep package manager

### ISSUE THREAD

**Issue by mkabilov** [zalando/postgres-operator#148]

**Comment by zerg-junior** [comment]
update:

1. `client-go` is [hard to update in projects that use `dep`](https://github.com/kubernetes/client-go/issues/78#issuecomment-387845808)
2. the [Go v1.11 modules are experimental](https://github.com/golang/go/wiki/Modules#go-111-modules)

So we probably should just stick with `glide` despite it not being developed since December/2017

**Comment by sdudoladov** [comment]
[Go Modules in 2019](https://blog.golang.org/modules2019)
> Our aim is for Go 1.13, scheduled for August 2019, to enable module mode by default (that is, to change the default from auto to on) and deprecate GOPATH mode. In order to do that, we’ve been working on better tooling support along with better support for the open-source module ecosystem.

we should move to modules in the near future.

**Comment by FxKu** [comment]
Go modules support got just merged :smiley:
