### ISSUE TITLE
Bug: master rejects connections for a few minutes

### ISSUE THREAD

**Issue by haslersn** [zalando/postgres-operator#1489]
Today at around 12:07:11 UTC in one of my Zalando postgres-operator PostgreSQL clusters, the master went down. It came back up at around 12:10:31 UTC. Here are the relevant files and logs from around that time:

- [Pod Environment ConfigMap](https://gist.github.com/haslersn/fb38fc92c5db507af2b4da7ac0e76c6a#file-kustomization-yaml)
- [Operator Configuration](https://gist.github.com/haslersn/fb38fc92c5db507af2b4da7ac0e76c6a#file-operator-config-yaml)
- [postgresql Manifest](https://gist.github.com/haslersn/fb38fc92c5db507af2b4da7ac0e76c6a#file-postgres-yaml)
- [postgresql-3.csv](https://gist.github.com/haslersn/fb38fc92c5db507af2b4da7ac0e76c6a#file-postgresql-3-csv)
- [postgresql-3.log](https://gist.github.com/haslersn/fb38fc92c5db507af2b4da7ac0e76c6a#file-postgresql-3-log)
- [kubectl logs](https://gist.github.com/haslersn/fb38fc92c5db507af2b4da7ac0e76c6a#file-stdout-log)

Answers to general questions:

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s via kubeadm
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

**Comment by haslersn** [comment]
Update: It seems all of our PostgreSQL clusters have been affected at around the same time.

**Comment by FxKu** [comment]
Looks like an issue then with your DCS / K8s API Server if all cluster where affected. In such cases Patroni demotes the master and promotes it back when the connection comes back. In between, recovery can take some more time:

`hydra-db-0 postgres 2021-05-12 12:08:19,385 INFO: demoted self because DCS is not accessible and i was a leader`
...
`hydra-db-0 postgres 2021-05-12 12:10:20,037 INFO: promoted self to leader because i had the session lock`

**Comment by FxKu** [comment]
Will close this one now due to lack of feedback.
