### ISSUE TITLE
Is this operator suites to big database on bare metal cluster?

### ISSUE THREAD

**Issue by thyn** [zalando/postgres-operator#1622]
As I understood everything is working for network volumes. Is it safe to use it in production on 2tb database bare metal?
I understood that pod migration won't work. Will master pod be restored in standby (replica state) after master failover? Or it should be manually reverted?

**Comment by sagor999** [comment]
As long as you have kubernetes running on top of your bare metal servers, then yes.
We have several fairly big PG databases running using this operator on our on-prem k8s clusters (running on bare metal) with no issues. 
>I understood that pod migration won't work. 
I am not sure why it would not work? Since you said cluster, I assume you have more then one bare metal server in your cluster, so if one server goes down, pod will be migrated to new node.
>Will master pod be restored in standby (replica state) after master failover? 
Yes. If your current master dies, replica will be promoted to master, and existing master pod will be restarted and will act as a replica node instead.

**Comment by thyn** [comment]
thank you
