### ISSUE TITLE
Rolling update required when we add custom lines to pg_hba.conf?

### ISSUE THREAD

**Issue by y-sira** [zalando/postgres-operator#1626]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.7.0`
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** GCP
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

Using this cluster manifest:

```shell-session
$ cat cluster.yaml 
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-cluster
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 3
  users:
    jonathan:
    - superuser
    - createdb
  databases:
    lusiadas: jonathan
  postgresql:
    version: "13"
  patroni:
    pg_hba:
      - local     all          all                        trust
      - hostssl   all          +zalandos 127.0.0.1/32     pam
      - host      all          all       127.0.0.1/32     md5
      - hostssl   all          +zalandos ::1/128          pam
      - host      all          all       ::1/128          md5
      - local     replication  standby                    trust
      - hostssl   replication  standby   all              md5
      - hostnossl all          all       all              reject
      - hostssl   all          +zalandos all              pam
      - hostssl   all          all       all              md5
    synchronous_mode: true
```

then all pods share the same `pg_hba.conf` including these lines:

```shell-session
$ kubectl exec acid-cluster-0 -- /bin/cat pgdata/pgroot/data/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
local     all          all                        trust
hostssl   all          +zalandos 127.0.0.1/32     pam
host      all          all       127.0.0.1/32     md5
hostssl   all          +zalandos ::1/128          pam
host      all          all       ::1/128          md5
local     replication  standby                    trust
hostssl   replication  standby   all              md5
hostnossl all          all       all              reject
hostssl   all          +zalandos all              pam
hostssl   all          all       all              md5
```

After adding these lines into the manifest file:

```diff
     pg_hba:
       - local     all          all                        trust
       - hostssl   all          +zalandos 127.0.0.1/32     pam
       - host      all          all       127.0.0.1/32     md5
       - hostssl   all          +zalandos ::1/128          pam
       - host      all          all       ::1/128          md5
       - local     replication  standby                    trust
       - hostssl   replication  standby   all              md5
       - hostnossl all          all       all              reject
       - hostssl   all          +zalandos all              pam
       - hostssl   all          all       all              md5
+      - host      all          all       10.4.0.0/16      trust
```

then rolling update had been started and all pods have been recreated.

Is this expected behavior?

**Comment by CyberDem0n** [comment]
> Is this expected behavior?

Yes

**Comment by Thoro** [comment]
@CyberDem0n  Sorry to add to the closed issue, but is there are possiblity to change this? A pg_hba change is usually nothing that requires a db restart, and it seems excessive to do a rolling upgrade on the whole cluster to force at least 2 promotions.

Also it looks like postgres-operator anyways calls the patroni api?

time="2021-11-09T12:52:57Z" level=debug msg="patching Postgres config via Patroni API on pod harbor/harbor-db-0 with following options: {\"pg_hba\":[\"local all all trust\",\"host  all all 127.0.0.1/32 trust\",\"host  all all ::1/128 trust\",\"local replication all trust\",\"host replication all 127.0.0.1/32 trust\",\"host replication all ::1/128 trust\",\"hostssl all all 0.0.0.0/0 md5\",\"host    all all 0.0.0.0/0 md5\"]}" cluster-name=harbor/harbor-db pkg=cluster
time="2021-11-09T12:52:57Z" level=debug msg="making PATCH http request: http://10.253.47.141:8008/config" cluster-name=harbor/harbor-db pkg=cluster

So, why do the patching, and a rolling upgrade?

(I am aware the rolling upgrade happens because the pg_hba is included in the SPILO config env variable)
