### ISSUE TITLE
Pooler Doesn't Work in Cloned Cluster

### ISSUE THREAD

**Issue by haslersn** [zalando/postgres-operator#1735]
When cloning a PostgreSQL cluster with pooler enabled, then the pooler doesn't work in the new cluster. The `pooler` user cannot connect. It seems to be a permission problem.

**Steps to reproduce**

1. Create a PostgreSQL cluster with pooler and wal-g backups enabled. (Maybe the same issue arises when using other backup/restore mechanisms.)
2. Create another PostgreSQL cluster as a clone of the previous cluster, also with pooler enabled.
3. Try to connect to the 2nd cluster with the `pooler` user. Observe:

   ```
   psql: error: FATAL:  permission denied for database "db"
   DETAIL:  User does not have CONNECT privilege.
   ```

   (In my example there's a database called `db`.) Above error of course implies that the pooler Deployment, created by the operator, cannot connect to the database either.

**Questions**

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.7.0`
- **Where do you run it** kubeadm 1.19 on bare metal
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

**Comment by FxKu** [comment]
@haslersn does this problem even persist after the clone is finished and the cluster is synced once?
When you create a clone, the operator would also create a new secret for the pooler user and update the DB to be in sync with the secret. Maybe you are still referencing the old secret from the source cluster. I can try to replicate, but first want to make sure, your're using the right secret.

What I can definitely say is, though, that standby clusters won't work with connection pooler enabled because the operator will try to install the pooler objects in the standby which won't work since it's a read-only cluster.

**Comment by haslersn** [comment]
> @haslersn does this problem even persist after the clone is finished and the cluster is synced once?

Yes, the issue persists on one of our cloned PostgreSQL clusters which is 43 days old.

> When you create a clone, the operator would also create a new secret for the pooler user and update the DB to be in sync with the secret. Maybe you are still referencing the old secret from the source cluster.

I don't think I reference the old secret from the source cluster. The new cluster has a different name than the source cluster and the new secret `pooler.test-clone-db.credentials` has been created 43 days ago, too. Also, when using wrong credentials, then the error is different (`FATAL:  password authentication failed for user "pooler"`).

> standby clusters won't work with connection pooler enabled

It's not a standby.

**Comment by FxKu** [comment]
> I don't think I reference the old secret from the source cluster. The new cluster has a different name than the source cluster and the new secret `pooler.test-clone-db.credentials` has been created 43 days ago, too. Also, when using wrong credentials, then the error is different (`FATAL: password authentication failed for user "pooler"`).

Indeed :smiley: 

I've tried to replicate it now, but it worked for me - pooler enabled on both source and cloned cluster. Took credentials from pooler secret and connected to the DB. My test cluster is empty however. Can you try to recreate the problem and check Postgres logs inside the container? If the problem is 43 days old already you probably won't find the original errors anymore (maybe operator pod logs).

Looking at the error message again I think your problem is that somebody revoked CONNECT privilege from PUBLIC role? This revokes CONNECT for every user to this DB.

**Comment by haslersn** [comment]
I'm trying, but I currently experience #1435 when cloning.

**Comment by haslersn** [comment]
I was not able to reproduce the issue. In other words: Now it works. I will reopen if it occurs with new clones again.
