### ISSUE TITLE
Docs Request: document updating a manifest

### ISSUE THREAD

**Issue by jberkus** [zalando/postgres-operator#181]
The current documentation doesn't explain how one updates a manifest for an existing cluster.

I'd write that myself, except that I've been unable to figure out how to do it with trial & error.

**Comment by alexeyklyukin** [comment]
Hi Josh,

Kubectl edit pg cluster-name is how I often do this. I think there is also a replace or apply command that works on CRDs, but I don’t have access to a cluster to experiment with this right now.

**Comment by alexeyklyukin** [comment]
actually both `kubectl apply` and `kubectl replace` work on a CRD with a reasonably modern client (mine reports 1.7.6 as a version.)

**Comment by jberkus** [comment]
I tried apply on 1.8 and got the error that the manifest already existed.

**Comment by mobilesfinks** [comment]
Same problem. When try to apply manifest - get error

> » ~/bin/google-cloud-sdk/bin/kubectl --context minikube apply -f ./manifests/minimal-postgres-manifest.yaml
> The postgresql "pg-cluster" is invalid: apiVersion: Invalid value: "postgresql": must be acid.zalan.do/v1
>
>  » cat ./manifests/minimal-postgres-manifest.yaml | grep apiVersion:
> apiVersion: acid.zalan.do/v1
>
> » kubectl --context minikube get postgresql pg-cluster -o yaml | grep apiVersion:
> apiVersion: acid.zalan.do/v1

Minikube version 1.8.0
Try with kubectl versions 1.7.5 and 1.9.2 - nothing change.

> kubectl --context minikube replace -f ./manifests/minimal-postgres-manifest.yaml   

Work correct

**Comment by alexeyklyukin** [comment]
@mobilesfinks it works for me (kubectl 1.8.2):
``
kubectl apply -f minimal-postgres-manifest.yaml
postgresql "acid-minimal-cluster" configured
``

Did you try to make any changes to the manifest before doing ``kubectl apply``? If I try it with the manifest that has not been changed since the last create/apply, I'm getting a  different, however, quite obscure error (version 1.8.2 for both the client and the server):

``
kubectl apply -f minimal-postgres-manifest.yaml
The postgresql "acid-minimal-cluster" is invalid: apiVersion: Invalid value: "acid.zalan.do/__internal": must be acid.zalan.do/v1
``

**Comment by FxKu** [comment]
Most `kubectl` options for this issue are mentioned here, I guess. I also use `edit`. Closing now. Anybody, feel free to reopen if still facing this problem.
