### ISSUE TITLE
Disable password rotation for single cluster

### ISSUE THREAD

**Issue by keliansb** [zalando/postgres-operator#1994]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare metal RKE
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** [Bug report, question, feature request, etc.] Question

Hello,

Is it possible to disable password rotation for a specific cluster? My use case is that I have an application ([Drone](https://github.com/harness/drone)) that does not use a specific secret for the database credentials. The credentials are specified directly in the connection URI. For example :
```
 postgresql://user:password@acid-drone:5432/drone?some_options
```
So when the operator will rotate the password this connection URI will not be updated.

Thanks in advance for your help.

**Comment by FxKu** [comment]
If your user is not listed in the manifest then there should be not secret for it, hence no rotation. I see that we also misuse the word "password rotation" here, because we only create new users and put their credentials in the secrets of the original user. The name and password of the latter remain unchanged.

But, we actually thought about an option to tune out from a globally enabled rotation of secrets - either on cluster or even user level.
