### ISSUE TITLE
Setting numberOfInstances to "2" instead of 2 will scale cluster to 0 replicas

### ISSUE THREAD

**Issue by cmeury** [zalando/postgres-operator#269]
## Steps

1. Create a cluster with 2 replicas
2. Wait until the cluster has been fully created
3. Edit the `postgresql` object and replace `2` by `"2"` (double quotes = string)

## Expectation

* The operator converts the string into an integer or reports an error.

## Observation

* The replica number is interpreted as 0 (see following log entry) and all pods are terminated.

```
time="2018-04-04T16:07:35Z" level=info msg="statefulset \"postgres/ric-zederich\" is not in the desired state and needs to be updated" cluster-name=postgres/ric-zederich pkg=cluster worker=2
postgres-operator-9f8cdc67c-n7x2h postgres-operator time="2018-04-04T16:07:35Z" level=debug msg="diff\nReplicas: 2 != 0\nSelector: &v1.LabelSelector{\n    MatchLabels:      {\"application\":\"spilo\", \"team\":\"ric\", \"version\":\"ric-zederich\"},\n    MatchExpressions: nil,\n} != nil\nTemplate.Spec.Containers[0].Resources.Limits[\"memory\"].s: \"1Gi\" != \"\"\nTemplate.Spec.Containers[0].TerminationMessagePath: \"/dev/termination-log\" != \"\"\nTemplate.Spec.Containers[0].TerminationMessagePolicy: \"File\" != \"\"\nTemplate.Spec.RestartPolicy: \"Always\" != \"\"\nTemplate.Spec.DNSPolicy: \"ClusterFirst\" != \"\"\nTemplate.Spec.DeprecatedServiceAccount: \"operator\" != \"\"\nTemplate.Spec.SecurityContext: &v1.PodSecurityContext{} != nil\nTemplate.Spec.SchedulerName: \"default-scheduler\" != \"\"\nTemplate.Spec.Tolerations: []v1.Toleration(nil) != []v1.Toleration{}\nVolumeClaimTemplates[0].Status.Phase: \"Pending\" != \"\"\nPodManagementPolicy: \"OrderedReady\" != \"\"\nUpdateStrategy.Type: \"OnDelete\" != \"\"\nRevisionHistoryLimit: &int32(10) != nil\n" cluster-name=postgres/ric-zederich pkg=cluster worker=2
```

**Comment by zerg-junior** [comment]
> Can you comment on this? Quick thinking is this is not so nice Go behavior, 

Yes, exactly. The operator at present relies on the JSON parsing provided by `golang`. Our `numOfInstances` field in the cluster struct is an integer, and when the golang json parser cannot parse the relevant field in the cluster manifest as an integer, it just uses the default value, which is zero for integers.

> the "CRD" Schema support which would prevent those mistakes early on with proper error message.

imho this is the much better way to prevent such issues than trying to fine tune the way we currently parse manifests. Otherwise we would have to use tricks with [struct ids](https://medium.com/@nate510/dynamic-json-umarshalling-in-go-88095561d6a0), which looks cumbersome
