### ISSUE TITLE
Questions regarding k8s version compatibility matrix change of v1.11.0 after the initial release

### ISSUE THREAD

**Issue by gc-jro** [zalando/postgres-operator#2700]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.11.0`
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** question

Hello,

we were wondering why the compatibility matrix of the initial release of operator version `v1.11.0` changed from
| Release   | Postgres versions | K8s versions      | Golang  |
| :-------- | :---------------: | :---------------: | :-----: |
| v1.11.*   | 11 &rarr; 16      | 1.21 &rarr; 1.28  | 1.21.7  |

to 
| Release   | Postgres versions | K8s versions      | Golang  |
| :-------- | :---------------: | :---------------: | :-----: |
| v1.11.0   | 11 &rarr; 16      | 1.27+             | 1.21.7  |

in [1], on May 31 2024, right when the `v1.12.0` release got out.

We are currently running the operator in Kubernetes 1.24 and are wondering
1) why the change was made,
2)  if we would have to expect any issues running with k8s 1.24, and
3) if there is an immediate need to downgrade on our side to operator release  `v1.10.1`.

I'm grateful for any insights in the compatibility matrix change.

If you need any further information please do not hesitate to contact me.

Best regards

Jens.

[1] https://github.com/zalando/postgres-operator/commit/6cde8e8c0b3e643df527f22ccf083f2c93253d17

**Comment by FxKu** [comment]
You're still on 1.24? ...wow
I made the change because some users reported that [a feature](https://github.com/zalando/postgres-operator/pull/2611) we introduced in 1.11.0 is not supported before 1.27.

There has also been a [change in the co-client](https://github.com/zalando/postgres-operator/issues/2603) in 1.29 which made me think operator will nit work on newer version unless I change the code. But, it's not an issue. We're on 1.30 and have now problems. Still, not sure though what happens if update dependencies and change the PVC code if it will work with version below 1.29...
