### ISSUE TITLE
Build recipe for spilo/patroni image

### ISSUE THREAD

**Issue by TeutoNet** [zalando/postgres-operator#499]
I'm currently trying to figure out how the spilo/patroni image `registry.opensource.zalan.do/acid/smoke-tested-postgres-operator` is build?

**Comment by Jan-M** [comment]
We have an internal test pipeline for the postgres operator image, it takes the one build from github.com (delivery.yaml) and then combined with the newest spilo it does some testing, from basic bootstrapping to migrations.

We are working on moving this to a public pipeline and tool chain so that everyone can run this.

This is desperately needed given the increased activity here.

**Comment by TeutoNet** [comment]
@Jan-M Thanks for the information. I was able to create my own CI script based on the mentioned `delivery.yaml` .
