### ISSUE TITLE
Register on operatorhub.io

### ISSUE THREAD

**Issue by hjacobs** [zalando/postgres-operator#508]
Postgres Operator should appear on https://www.operatorhub.io/ :smile:

**Comment by FxKu** [comment]
Added a [PR](https://github.com/operator-framework/community-operators/pull/210). Let's see what their feedback is.

**Comment by sdudoladov** [comment]
@FxKu pls consider documenting how to deploy the Postgres operator on the infra assumed by other operator from  https://www.operatorhub.io Otherwise users who find us through this catalog may be confused due to differences in terminology /  conf options (CRD vs ConfigMap) etc.

One section in the "Admin docs" will imho do

**Comment by FxKu** [comment]
PR got merged. I will do some tests via this framework and extend the admin docs if needed.

**Comment by FxKu** [comment]
After a fix got merged too, it is now working as expected:
```
# install OLM
curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.10.0/install.sh | bash -s 0.10.0

# install Postgres Operator
kubectl create -f https://operatorhub.io/install/postgres-operator.yaml
```

**Comment by FxKu** [comment]
Closing this one now. Updated it after the release of `v1.2.0` and it's documented in the quickstart.
