### ISSUE TITLE
Implement the kubectl plugin for the Postgres CustomResourceDefinition

### ISSUE THREAD

**Issue by VineethReddy02** [zalando/postgres-operator#519]
@sdudoladov  As this proposal doesn't have issue tracker, I have created one. And everyone can share their views, design related suggestions and functionalities such delete, auto-completion of resource names etc...

**Comment by sdudoladov** [comment]
@VineethReddy02 we expect you to contribute your own ideas, it is your proposal after all

a few starting points to consider (not mandatory or even necessary)

```bash
# correct deletion of a PG cluster, with warnings/confirmation requests
kubectl postgresql delete your-cluster-name

# compare manifest with the actual state of the cluster stored in the operator
kubectl postgresql diff your-cluster-name 

# convenience alias for normal manifest editing 
kubectl postgresql update your-cluster-name

# trickier: aliases for common Patroni commands
kubectl postgresql reinit replica-name

# short name for the command 
kubectl pg ...
kubectl postgresql

# ideally autocompletion
```


@erthalion @FxKu @Jan-M pls have a look

**Comment by erthalion** [comment]
```sh
# trickier: aliases for common Patroni commands
kubectl postgresql reinit replica-name
```

I doubt it makes sense to implement something like this, since it has to be interactive and full of confirmation that you really want to do this (that's the point of patronictl). But at the same time this should be implemented outside of patronictl, which means code duplication and dependency.

**Comment by sdudoladov** [comment]
We are pleased to announce that this project was accepted to the GSoC 2019. Congratulations, @VineethReddy02  !

Vineeth, we are now in the community bonding period, and we would like to use this an opportunity to introduce  you to our community and vice versa. Our suggestion for this period is straightforward:
* You should (if not already) familiarize yourself with the most important concepts behind the operator and prepare the development environment to ensure you are ready to start coding in 2 weeks. So:
- [ ] do the k8s tutorial of your choice 
- [ ] do [the PG operator quickstart](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md) to get idea of basic abstractions and read / update [user](https://github.com/zalando/postgres-operator/blob/master/docs/user.md) and [admin](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md) docs as they are directly relevant to your project
- [ ] brush up tools if necessary: git and golang. A basic tutorial will do, have a look at [https://learnxinyminutes.com/](https://learnxinyminutes.com/) 
- [ ] study k8s plugin architecture. Read [the docs](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) and [skim the sample plugin](https://github.com/kubernetes/sample-cli-plugin)  to get idea of how they are implemented. 
* Finalize the deliverables:
1. The project goal is to develop a `kubectl` plugin for the Postgres operator
2. The progress is to be reported weekly on Friday afternoons as a message formatted according tho the template below.  A comment in this issue will do,  or you may go with the blogging platform of your choice.
3. The real-time communication is to be done in the postgres-operator slack channel. Since we are an OSS project we strongly prefer public communication and discourage private message unless in exceptional circumstances
4. The development is to be done in a separate PR to the operator repository. We believe moving the development to an independent repo will separate you too much form the community.
5. We expect mergeable code at the end of each milestone. This means readable documented code that does what it is supposed to do and handles basic corner cases.
6. The deliverables / milestones must follow the page 6 in the proposal. 
 

Report template:
### Calendar week \#0
* Summary of the things done last week
* What can be improved
* What went well
* TODOs for the upcoming week. For new commands these must include sketch of the usage string as in
```bash
# correct deletion of a PG cluster, with warnings/confirmation requests
kubectl postgresql delete your-cluster-name
```

Please inform us if you have an instable Internet connection and any planned absences.
Finally, keep in mind that it is still not core GSoC, so you are not expected to work full-time :) 

@VineethReddy02 before we embark on these tasks, we would like to hear you feedback on the suggestions.

@FxKu will be a 2nd mentor, so his comments will be well appreciated  :)

**Comment by VineethReddy02** [comment]
Thank you, Sergey! for the introduction.
- I have already set up my machine with all the required installations.
- I also have a stable internet connection. If there are any sudden circumstances I will let you know in advance.
- Going forward during the community bonding period I will spend time in understanding k8s, PG Operator(especially) and k8s plugin architecture. 
- From now on I will prefer Postgres-operator slack channel for communication.
- I will follow the above-mentioned template for updating weekly progress. I will update in my public repository [here](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker).
- So kubectl pg plugin will be part of the operator repository in a separate folder. Just to make sure, I don't think it should be a problem to the operator repository to have some dependencies vendored that are required by the plugin.

Looking forward to working with you all! 
@sdudoladov @FxKu

**Comment by sdudoladov** [comment]
> I will follow the above-mentioned template for updating weekly progress. I will update in my public repository here.

Sounds good. We will then post links from it in this repo. 

> So kubectl pg plugin will be part of the operator repository in a separate folder. Just to make sure, I don't think it should be a problem to the operator repository to have some dependencies vendored that are required by the plugin.

At this point it should not be much of a problem. Much more important is that you do not stay too far away from the mainline operator development.

**Comment by VineethReddy02** [comment]
As the Community bonding period started on May 7 I will update both the week's progress summary by end of this week. So that you review the last two weeks progress summary.

I totally understood your intention for having kubectl plugin work within operator repo. I am happy that I can work closely with the community.  :100: 

Thanks!

**Comment by VineethReddy02** [comment]
I will be updating the work on kubectl plugin development [here](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker). This acts as a tracker which comprises of proposal, design docs and any further discussions on implementation with weekly reports.

**Comment by sdudoladov** [comment]
@VineethReddy02 please provide the weekly report for the last week. The coding officially starts today :)

**Comment by VineethReddy02** [comment]
Hey, @sdudoladov  I forgot to commit the summary committed it yesterday after our call. Thanks for your time. I have started coding.

**Comment by sdudoladov** [comment]
@VineethReddy02 
> I was validating kubectl pg check by the status of postgres operator deployment status. But when i realised crd can be deleted manually and operator status is still running. My initial work fails. I should have done this validations before writing the code.

your work does not fail; you just need to check that the [operator deployment exits and has one replica](https://github.com/zalando/postgres-operator/blob/19fa91eaacf8d03301af1a7d6b2dd7a9041b0074/manifests/postgres-operator.yaml#L6)

**Comment by VineethReddy02** [comment]
@sdudoladov 
1.
Initially, I was validating the number of replicas as well. but when CRD is deleted manually. CRD check for postgresql fails. After CRD deleted manually operator is in running state. Which doesn't work for the CRD manually deleted usecase.

	for _,deployment := range allDeployments.Items {
		if(deployment.Name=="postgres-operator" && deployment.Status.ReadyReplicas>=1){
			fmt.Println("postgresql CRD Successfully Registered.")
			registered = true
			break
		}
	}
	if(!registered) {
			fmt.Println("Make sure Postgres-Operator is running.")
	}

2. 
Example commands for this week work
**Create/update/delete of  kind:postgresql** 
```
# This will create postgresql cluster
kubectl pg create abc.yaml

# This will update existing cluster with latest changes
kubectl pg update abc.yaml 

# This will delete the postgresql cluster by filename.yaml/postgresql-cluster-name
kubectl pg delete abc.yaml/postgresql_name
```

**Comment by sdudoladov** [comment]
> but when CRD is deleted manually. CRD check for postgresql fails. After CRD deleted manually operator is in running state.

if you delete the operator CRD and restart the operator pod, does the pod fail ?

>  This will delete the postgresql cluster by filename.yaml/postgresql-cluster-name
kubectl pg delete abc.yaml/postgresql_name

start with that one, it is actually important. The command has to ask for confirmation (as in "are you sure you want to delete the cluster-name ? [y/N]" with "No" being the default) and show a success message saying the cluster manifest has been deleted and related objects will be garbaged collected by the k8s/operator. It also has to include a help message saying that only manifest deletion is necessary to delete a DB ( a common mistake is to delete other objects manually only to see them re-created by the operator later)

I'd also split the command in 2 forms:
```bash
kubectl pg delete postgresql_name
kubectl pg delete --file cluster-manifest.yaml
```
to match conventions from the original kubectl delete

> kubectl pg create *--file*  abc.yaml
> kubectl pg update *--file* abc.yaml 

these should be simple wrapper commands, do not spend much time on them

**Comment by VineethReddy02** [comment]
On deletion of CRD i.e ``` kubectl delete crds/postgresqls.acid.zalan.do``` The state of the postgres operator is still running and the validation by evaluating the status of operator fails. Let me know if am missing something.

![Screenshot (17)](https://user-images.githubusercontent.com/25104868/58805841-7f13c680-8632-11e9-873f-de42aef3576d.png)

I will start working on the delete, create and update commands as discussed. 

Thanks!

**Comment by VineethReddy02** [comment]
As per the discussion with @sdudoladov @FxKu 
Implementation of adding USER, DB, and extending the VOLUME. 
The format of commands will look like

Adding USER
```kubectl pg add-user XYZ -clusterName  cluster01```

Adding DB and associated OWNER 
```kubectl pg add-db XYZ -owner zalando -cluster cluster01```

Extending the existing volume size
```kubectl pg ext-volume 2Gi -clusterName cluster01```

Please feel free to share your views on this.
Thanks!

**Comment by sdudoladov** [comment]
weekly summaries from Vineeth for the record
* [week 3](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker/blob/master/weekly/week3.md) 
* [week 4](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker/blob/master/weekly/week4.md)
* [week 5](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker/blob/master/weekly/week5.md)

**Comment by sdudoladov** [comment]
[week 6](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker/blob/master/weekly/week6.md)

**Comment by sdudoladov** [comment]
[week 7](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker/blob/master/weekly/week7.md)

**Comment by sdudoladov** [comment]
[week 8](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker/blob/master/weekly/week8.md)
[week 9](https://github.com/VineethReddy02/GSoC-Kubectl-Plugin-for-Postgres-Operator-tracker/blob/master/weekly/week9.md)

**Comment by hjacobs** [comment]
Related: #635

**Comment by FxKu** [comment]
Closing as PR got merged.
