### ISSUE TITLE
Do not deploy OperatorConfiguration resource unless CRD based configuration was enabled

### ISSUE THREAD

**Issue by Bryji** [zalando/postgres-operator#606]
I lost a fair amount of time trying to figure out why changes I was deploying were making it to the OperatorConfiguration CRD but having no effect until I spotted that it can be configured via ConfigMap or CRD (I guess there is some reason it can't just be ConfigMap?)

It would be good to not deploy to OperatorConfiguration resource (and maybe CRD itself) if ConfigMap configuration is being used, e.g. surrounding it with something like:

```
{{- if .Values.POSTGRES_OPERATOR_CONFIGURATION_OBJECT -}}
apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
...
{{- end -}}
```

**Comment by FxKu** [comment]
Looks like you are using the helm chart. In the current form it creates both a ConfigMap and OperatorConfiguration resource. But only the object referenced in the [`env`](https://github.com/zalando/postgres-operator/blob/ff80fc4d0ffc2e2c97eef44df8e89d38c7f503c1/manifests/postgres-operator.yaml#L33) section of the deployment is taken into account. So, ideally there should only exist one of the config resources, which is why I have also split the `values.yaml` in PR #595 and put one template into `.helmignore` file.

Some more reasoning can also be found in #367.

**Comment by FxKu** [comment]
PR got merged. Thanks again for the idea of putting the if around the whole template. Now it's pretty easy to choose either ConfigMap or CRD-based configuration.

**Comment by Bryji** [comment]
👍
