### ISSUE TITLE
Restoring cluster from backup on non-AWS s3

### ISSUE THREAD

**Issue by thepotatocannon** [zalando/postgres-operator#665]
Hi, I'm stuck at restoring cluster from S3. Every time I create a cluster from a manifest with clone section, the cluster is initialized without any data from a backup. I sadly cannot find out where the problem is. Please let me know kind of information you need to help, I will be happy to provide it.

Backups are made by a cronjob, performing dump on a database, the one from this project.

Backups are located at path:
http://minio:9000//<BUCKET_NAME>/spilo/<CLUSTER_NAME>/<CLUSTER_UID>/logical_backups/

Here is my clone section:
  clone:
    uid: "CLUSTER_UID"
    cluster: "CLUSTER_NAME"
    timestamp: "2019-09-09T13:15:00+00:00"
    s3_endpoint: http://minio:9000//<BUCKET_NAME>/spilo
    s3_access_key_id: ACCESS_KEY_ID
    s3_secret_access_key: SECRET_ACCESS_KEY
    s3_force_path_style: true

Could it be connected with a warning I get while bootstapping?
`2019-09-10 10:50:42,612 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2019-09-10 10:50:45,311 - bootstrapping - WARNING - Cloning with WAL-E is only possible when CLONE_WALE_*_PREFIX or CLONE_WALG_*_PREFIX or CLONE_WAL_*_BUCKET and CLONE_SCOPE are set.
`

**Comment by Jan-M** [comment]
How does the pod spec look like for the pod doing the clone? Does it contain the clone fields?

Code:
https://github.com/zalando/postgres-operator/blob/1d45a6aec3aa468a5184874af90adaba12fbf3e2/pkg/cluster/k8sres.go#L1302

Dont know immediate answer.

**Comment by thepotatocannon** [comment]
These are CLONE envs from spec:
      CLONE_SCOPE:                    <CLUSTER_NAME>
      CLONE_WAL_S3_BUCKET:            
      CLONE_WAL_BUCKET_SCOPE_SUFFIX:  /<CLONE_UID>
      CLONE_METHOD:                   CLONE_WITH_WALE
      CLONE_TARGET_TIME:              2019-09-09T13:15:00+00:00
      CLONE_WAL_BUCKET_SCOPE_PREFIX:  
      CLONE_AWS_ENDPOINT:             http://minio-kamil:9000//<BUCKET_NAME>/spilo
      CLONE_WALE_S3_ENDPOINT:         http://minio-kamil:9000//<BUCKET_NAME>/spilo
      CLONE_AWS_ACCESS_KEY_ID:        <ACCESS_KEY_ID>
      CLONE_AWS_SECRET_ACCESS_KEY:    <SECRET_ACCESS_KEY>
      CLONE_AWS_S3_FORCE_PATH_STYLE:  1

Values in <ENV VALUE> are the same as I specified in clone section of manifest.

**Comment by thepotatocannon** [comment]
These are CLONE envs from spec:
CLONE_SCOPE: <CLUSTER_NAME>
CLONE_WAL_S3_BUCKET:
CLONE_WAL_BUCKET_SCOPE_SUFFIX: /<CLONE_UID>
CLONE_METHOD: CLONE_WITH_WALE
CLONE_TARGET_TIME: 2019-09-09T13:15:00+00:00
CLONE_WAL_BUCKET_SCOPE_PREFIX:
CLONE_AWS_ENDPOINT: http://minio:9000//<BUCKET_NAME>/spilo
CLONE_WALE_S3_ENDPOINT: http://minio:9000//<BUCKET_NAME>/spilo
CLONE_AWS_ACCESS_KEY_ID: <ACCESS_KEY_ID>
CLONE_AWS_SECRET_ACCESS_KEY: <SECRET_ACCESS_KEY>
CLONE_AWS_S3_FORCE_PATH_STYLE: 1

Values in are the same as I specified in clone section of manifest.

**Comment by thepotatocannon** [comment]
This might be connected with the fact, that CLONE_METHOD is CLONE_WITH_WALE, probably should be CLONE_WITH_BASEBACKUP? If so, where do I set up this value?

**Comment by thepotatocannon** [comment]
@Jan-M is it even possible? Or at the moment you can do it only with WAL-E from S3? But if it is so, then you can only do it from AWS, as scripts do not check for the endpoint for non-AWS environment?

**Comment by Jan-M** [comment]
@CyberDem0n can you help here?

**Comment by CyberDem0n** [comment]
If Spilo will get env variables mentioned in the [comment](https://github.com/zalando/postgres-operator/issues/665#issuecomment-529895653) it should create a new cluster from the backup.

**Comment by F00dwarrior** [comment]
I stumbled over this issue as I was trying the same, creating a cluster from a logical backup.
In my understanding this is not possible at the moment.

> This might be connected with the fact, that CLONE_METHOD is CLONE_WITH_WALE, probably should be CLONE_WITH_BASEBACKUP? If so, where do I set up this value?
There are two Options for Cloning, `CLONE_WITH_BASEBACKUP` or `CLONE_WITH_WALE`. The right one is chosen automatically (Line 1319 in pkg/cluster/k8res.go). So if there is a timestamp defined in the clone section from the cluster, `CLONE_WITH_WALE` is chosen. This is the case in your example.
If you would omit the timestamp, `CLONE_WITH_BASEBACKUP` would be chosen. But this won't help you either as this option is used to create a clone from another cluster, which is running at the same time in the same namespace. I think it would be possible to create an option which fetches an dump from s3 instead of creating a dump from a different cluster and importing this, but this is a change for Patroni (as an alternative to clone_with_basebackup.py and clone_with_wale.py).

> If Spilo will get env variables mentioned in the [comment](https://github.com/zalando/postgres-operator/issues/665#issuecomment-529895653) it should create a new cluster from the backup.
I do not think that this is true. As @thepotatocannon pointed out, WAL-G refuses to do anything at the container startup ("Cloning with WAL-E is only possible when CLONE_WALE_*_PREFIX or CLONE_WALG_*_PREFIX or CLONE_WAL_*_BUCKET and CLONE_SCOPE are set."), because some environment variables (in this case the PREFIX) are missing. The `s3_wal_path` variable needs to be defined in the clone section from the cluster so that the operator is building the PREFIX environment variable correctly and afterwards WAL-G can connect to s3, fetch the data and import it.
