### ISSUE TITLE
Ability to add SSL certificate for S3

### ISSUE THREAD

**Issue by aurelienmarie** [zalando/postgres-operator#845]
I am currently testing the operator and running Minio for S3 storage. I managed to do the logical backup with TLS disabled on Minio and it works fine.

However, i have this issue when i enable the TLS on Minio.

```
+ dump
+ /usr/lib/postgresql/10/bin/pg_dumpall
+ compress
+ pigz
++ estimate_size
++ /usr/lib/postgresql/10/bin/psql -tqAc 'select sum(pg_database_size(datname)::numeric) from pg_database;'
+ aws_upload 6377860
+ declare -r EXPECTED_SIZE=6377860
++ date +%s
+ PATH_TO_BACKUP=s3://databases/spilo/test-test-cluster/575fa115-2b52-4972-b4e2-e59fe967f962/logical_backups/1582638557.sql.gz
+ args=()
+ [[ ! -z 6377860 ]]
+ args+=("--expected-size=$EXPECTED_SIZE")
+ [[ ! -z https://minio.default.svc.cluster.local:9000 ]]
+ args+=("--endpoint-url=$LOGICAL_BACKUP_S3_ENDPOINT")
+ [[ ! -z '' ]]
+ aws s3 cp - s3://databases/spilo/test-test-cluster/575fa115-2b52-4972-b4e2-e59fe967f962/logical_backups/1582638557.sql.gz --expected-size=6377860 --endpoint-url=https://minio.default.svc.cluster.local:9000
upload failed: - to s3://databases/spilo/test-test-cluster/575fa115-2b52-4972-b4e2-e59fe967f962/logical_backups/1582638557.sql.gz SSL validation failed for https://minio.default.svc.cluster.local:9000/databases/spilo/test-test-cluster/575fa115-2b52-4972-b4e2-e59fe967f962/logical_backups/1582638557.sql.gz [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```

I've build my own docker image for backups adding `args+=("--no-verify-ssl")` in the `dump.sh`. As a result, i was able to backup my db with TLS enable on Minio.

The idea here is to add a parameter on the operatorconfiguration in order to either be able to specify a certificate, or disable the ssl verification.

Zalando postgres-operator version : v1.3.1

**Comment by FxKu** [comment]
There is currently a PR open to add TLS support for database pods. At the moment, the TLS volume is [not passed](https://github.com/zalando/postgres-operator/blob/d152ea9a4a57e853c7ac20f55eb27189fb547b09/pkg/cluster/k8sres.go#L1591) to the logical backup pod. Would this be useful for you?

**Comment by aurelienmarie** [comment]
@FxKu my issue is not related to the TLS support for database pods but for the the backups cronjobs. It's required for wal-e/wal-g in order to target the S3 endpoint.

**Comment by Jonher937** [comment]
I also had this problem today.
This happens when using a S3 server that does not have a valid signed certificate.

It would be nice if the operator could accept something like a base64 encoded PEM certificate, this would then be passed to the Logical Backup container as a environment variable where `dump.sh` could `base64 -d` the content and save that to a `mktmp` file or similar. 

Appending `--ca-bundle=$CA_FILE"` to the aws cli so verification is in place instead of using `--insecure` (or allowing for both options)

**Comment by blyry** [comment]
You can workaround this by using letsencrypt and putting a valid certificate on your minio deployment. You don't even need to make your endpoint public now that most dns providers support api based cname validation! That seems like a 'better' solution than supporting the `--insecure` on their own implementation. 

Supporting custom TLS or root CAs on the operator side is also a good feature to add though, but then you still have to go through the process of signing, deploying and managing a cert for your minio installation.

**Comment by DrissiReda** [comment]
Is it possible to disable ssl altogether for minio logical backups? I can't find the option in documentation.

**Comment by alexzimmer96** [comment]
Is there any update? We are also facing the issue, that backing up to a remote minio instance fails because of self signed certificates. We do not control the minio, so it it is not that easy to change the certificates. I have are some workarounds in my mind (like adding a cluster-internal reverse proxy), but they would be some kind of hacky.

**Comment by thangamani-arun** [comment]
@FxKu we are really looking `--insecure` or `--tls-no-verify` kind of flags for logical volumes, since there are no way to add CA cert to the pod. Please consider as needed feature.

**Comment by alexanderheckel** [comment]
You can use `additionalVolumes` to add the CA certificate to the database pod and set `WALG_S3_CA_CERT_FILE` pointing to the mounted file.

```yaml
  additionalVolumes:
    - name: minio-ca-certificate
      mountPath: /certs/minio
      targetContainers: []
      volumeSource:
        secret:
          secretName: minio-ca-certificate
```

```yaml
  env:
    - name: WALG_S3_CA_CERT_FILE
      value: "/certs/minio/ca.crt"
```

**Comment by DekelDevunet** [comment]
+1

**Comment by vponnathota** [comment]
> You can use `additionalVolumes` to add the CA certificate to the database pod and set `WALG_S3_CA_CERT_FILE` pointing to the mounted file.
> 
> ```yaml
>   additionalVolumes:
>     - name: minio-ca-certificate
>       mountPath: /certs/minio
>       targetContainers: []
>       volumeSource:
>         secret:
>           secretName: minio-ca-certificate
> ```
> 
> ```yaml
>   env:
>     - name: WALG_S3_CA_CERT_FILE
>       value: "/certs/minio/ca.crt"
> ```

I followed the same steps but still failed to upload backups to minio s3 , can i get some help here

k get pods -n zalando
NAME                                        READY   STATUS    RESTARTS   AGE
abc-time-0                                  1/1     Running   0          43h
abc-time-1                                  1/1     Running   0          43h
abc-time-2                                  1/1     Running   0          43h
logical-backup-abc-time-27964140--1-8x5qm   0/1     Error     0          32m
logical-backup-abc-time-27964140--1-hf4cf   0/1     Error     0          23m
logical-backup-abc-time-27964140--1-ncfkg   0/1     Error     0          33m
logical-backup-abc-time-27964140--1-nwfhw   0/1     Error     0          32m
logical-backup-abc-time-27964140--1-t5rd7   0/1     Error     0          31m
logical-backup-abc-time-27964140--1-vrc5j   0/1     Error     0          29m
logical-backup-abc-time-27964140--1-xszth   0/1     Error     0          17m
postgres-operator-7486f85b89-qndjv          1/1     Running   0          6d17h
k logs logical-backup-abc-time-27964140--1-xszth -n zalando
IPv4
API Endpoint: https://x.x.x.x:443/api/v1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14170    0 14170    0     0  1383k      0 --:--:-- --:--:-- --:--:-- 1383k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0  15181      0 --:--:-- --:--:-- --:--:-- 15181
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0  20875      0 --:--:-- --:--:-- --:--:-- 20875
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19762    0 19762    0     0  2412k      0 --:--:-- --:--:-- --:--:-- 2412k
+ '[' s3 == az ']'
+ dump
+ /usr/lib/postgresql/14/bin/pg_dumpall
+ upload
+ case $LOGICAL_BACKUP_PROVIDER in
+ compress
+ pigz
++ estimate_size
++ /usr/lib/postgresql/14/bin/psql -tqAc 'select sum(pg_database_size(datname)::numeric) from pg_database;'
+ aws_upload 9359286
+ declare -r EXPECTED_SIZE=9359286
++ date +%s
+ PATH_TO_BACKUP=s3://abctimedb/spilo/abc-time/9c439c23-7c1d-4dd0-8ed9-7027bde17825/logical_backups/1677849333.sql.gz
+ args=()
+ [[ ! -z 9359286 ]]
+ args+=("--expected-size=$EXPECTED_SIZE")
+ [[ ! -z https://minio.minio-abc.svc.cluster.local:443 ]]
+ args+=("--endpoint-url=$LOGICAL_BACKUP_S3_ENDPOINT")
+ [[ ! -z '' ]]
+ [[ ! -z '' ]]
+ aws s3 cp - s3://abctimedb/spilo/abc-time/9c439c23-7c1d-4dd0-8ed9-7027bde17825/logical_backups/1677849333.sql.gz --expected-size=9359286 --endpoint-url=https://minio.minio-abc.svc.cluster.local:443
pg_dump: warning: there are circular foreign-key constraints on this table:
pg_dump:   hypertable
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: warning: there are circular foreign-key constraints on this table:
pg_dump:   chunk
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: warning: there are circular foreign-key constraints on this table:
pg_dump:   continuous_agg
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
/usr/local/lib/python3.6/dist-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.bindings.openssl.binding import Binding
upload failed: - to s3://abctimedb/spilo/abc-time/9c439c23-7c1d-4dd0-8ed9-7027bde17825/logical_backups/1677849333.sql.gz SSL validation failed for https://minio.minio-abc.svc.cluster.local:443/abctimedb/spilo/abc-time/9c439c23-7c1d-4dd0-8ed9-7027bde17825/logical_backups/1677849333.sql.gz?uploads [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

**Comment by thangamani-arun** [comment]
but the operator keeps on recreating the pods due to difference in the pod spec(additional volume in postgres )

**Comment by D1StrX** [comment]
running into the exact same issue. Would be nice if a custom ca could be mounted

**Comment by thangamani-arun** [comment]
@FxKu : Can you guys fix this as a priority?

**Comment by ErikLundJensen** [comment]
If your CA used for the Postgress tls certificate is the same as your S3 backend's CA then you can reuse the ca.crt mounted into the postgres container. For example as environment variable:
```
env:
- name: WALG_S3_CA_CERT_FILE
  value: "/tls/ca.crt"
```
or add to the ConfigMap for the Postgres Operator if using the `pod_environment_configmap` in the Helm chart:
```
WALG_S3_CA_CERT_FILE: "/tls/ca.crt"
```

**Comment by sreenandan** [comment]
I figured this out, the problem is with which IPs allowed with ca.crt.
Bitnami minio helm chart auto-gen certs allows connections only to the k8s service ip and I was using host ip with nodeport which wont work.
I changed AWS_ENDPOINT from https://10.9.20.45:31734 to https://minio.default.svc.cluster.local:9000 and wal-g is not stuck anymore, things are flowing.

**Comment by thangamani-arun** [comment]
I think the issue is not resolved. The problem here is that the S3 SSL cert is a self-signed cert. Hence the backup job pods don't have S3' CA cert. Hence it will fail to run backup job.

adding a CA volume as removed by postgres-operator due to difference it spec. Hence that solution is also doesn't work. 

But @FxKu has closed the issue now. any reason why?
