### ISSUE TITLE
[Question] How to upgrade?

### ISSUE THREAD

**Issue by vitobotta** [zalando/postgres-operator#849]
Hi! I recently contributed a minor change to add the region setting for logical backups. Now that this and several improvements have been merged with the latest release I would like to upgrade my operator and clusters to use the official images. The version of the operator I am using now is v1.13.3. How do I upgrade to the latest 1.4.0? I can't find this info. Do I just change the images? Or do I reapply the manifests? I haven't tried yet because I don't want to screw things up :p

Thanks!

**Comment by FxKu** [comment]
Right, upgrading is not documented as it's really this simple by changing the image and/or reapplying the manifests. We always do the latter, in case - like with this release - things in the config map or RBAC change.

Have a look at the breaking changes. The operator will now use the `postgres-pod` [cluster role](https://github.com/zalando/postgres-operator/blob/master/manifests/operator-service-account-rbac.yaml#L210) for statefulsets and pods. But it does not create this role, so it has to be there before changing the deployment. If you are using the config map and do not specify a cluster name label the key would now be different: `cluster-name` instead of `version`.

**Comment by vitobotta** [comment]
@FxKu Oh I thought the image for the logical backups had been updated as well. I can use mine for now. I am not in rush to upgrade so I can do this when that image has been updated as well. How can I be notified when this happens? Will you publish a new release? Thanks!

**Comment by FxKu** [comment]
Added a [paragraph](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#upgrading-the-operator) a few months ago.
